# Generated by Django 3.1.5 on 2021-02-25 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.poster', verbose_name='Объявление'),
        ),
    ]
